# Generated by Django 5.2.2 on 2025-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
